language: java
sudo: required

jdk:
  - openjdk7

sudo: required

install:
  - ./install.sh --install-only 2>&1 >install.log

script:
  - travis_wait (cd web-cat/Web-CAT && ant build.subsystems build.redistributable.war)
